// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kinect_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "kinect_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* log_packet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  log_packet_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_kinect_5fmessage_2eproto() {
  protobuf_AddDesc_kinect_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "kinect_message.proto");
  GOOGLE_CHECK(file != NULL);
  log_packet_descriptor_ = file->message_type(0);
  static const int log_packet_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, depth_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, color_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, body_),
  };
  log_packet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      log_packet_descriptor_,
      log_packet::default_instance_,
      log_packet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(log_packet));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_kinect_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    log_packet_descriptor_, &log_packet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_kinect_5fmessage_2eproto() {
  delete log_packet::default_instance_;
  delete log_packet_reflection_;
}

void protobuf_AddDesc_kinect_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024kinect_message.proto\"8\n\nlog_packet\022\r\n\005"
    "depth\030\001 \003(\r\022\r\n\005color\030\002 \003(\014\022\014\n\004body\030\003 \003(\001", 80);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kinect_message.proto", &protobuf_RegisterTypes);
  log_packet::default_instance_ = new log_packet();
  log_packet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_kinect_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_kinect_5fmessage_2eproto {
  StaticDescriptorInitializer_kinect_5fmessage_2eproto() {
    protobuf_AddDesc_kinect_5fmessage_2eproto();
  }
} static_descriptor_initializer_kinect_5fmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int log_packet::kDepthFieldNumber;
const int log_packet::kColorFieldNumber;
const int log_packet::kBodyFieldNumber;
#endif  // !_MSC_VER

log_packet::log_packet()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:log_packet)
}

void log_packet::InitAsDefaultInstance() {
}

log_packet::log_packet(const log_packet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:log_packet)
}

void log_packet::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

log_packet::~log_packet() {
  // @@protoc_insertion_point(destructor:log_packet)
  SharedDtor();
}

void log_packet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void log_packet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* log_packet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return log_packet_descriptor_;
}

const log_packet& log_packet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_kinect_5fmessage_2eproto();
  return *default_instance_;
}

log_packet* log_packet::default_instance_ = NULL;

log_packet* log_packet::New() const {
  return new log_packet;
}

void log_packet::Clear() {
  depth_.Clear();
  color_.Clear();
  body_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool log_packet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:log_packet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 depth = 1;
      case 1: {
        if (tag == 8) {
         parse_depth:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 8, input, this->mutable_depth())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_depth())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(8)) goto parse_depth;
        if (input->ExpectTag(18)) goto parse_color;
        break;
      }

      // repeated bytes color = 2;
      case 2: {
        if (tag == 18) {
         parse_color:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_color()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_color;
        if (input->ExpectTag(25)) goto parse_body;
        break;
      }

      // repeated double body = 3;
      case 3: {
        if (tag == 25) {
         parse_body:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 25, input, this->mutable_body())));
        } else if (tag == 26) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_body())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_body;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:log_packet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:log_packet)
  return false;
#undef DO_
}

void log_packet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:log_packet)
  // repeated uint32 depth = 1;
  for (int i = 0; i < this->depth_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      1, this->depth(i), output);
  }

  // repeated bytes color = 2;
  for (int i = 0; i < this->color_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->color(i), output);
  }

  // repeated double body = 3;
  for (int i = 0; i < this->body_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      3, this->body(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:log_packet)
}

::google::protobuf::uint8* log_packet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:log_packet)
  // repeated uint32 depth = 1;
  for (int i = 0; i < this->depth_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(1, this->depth(i), target);
  }

  // repeated bytes color = 2;
  for (int i = 0; i < this->color_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->color(i), target);
  }

  // repeated double body = 3;
  for (int i = 0; i < this->body_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(3, this->body(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:log_packet)
  return target;
}

int log_packet::ByteSize() const {
  int total_size = 0;

  // repeated uint32 depth = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->depth_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->depth(i));
    }
    total_size += 1 * this->depth_size() + data_size;
  }

  // repeated bytes color = 2;
  total_size += 1 * this->color_size();
  for (int i = 0; i < this->color_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->color(i));
  }

  // repeated double body = 3;
  {
    int data_size = 0;
    data_size = 8 * this->body_size();
    total_size += 1 * this->body_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void log_packet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const log_packet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const log_packet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void log_packet::MergeFrom(const log_packet& from) {
  GOOGLE_CHECK_NE(&from, this);
  depth_.MergeFrom(from.depth_);
  color_.MergeFrom(from.color_);
  body_.MergeFrom(from.body_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void log_packet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void log_packet::CopyFrom(const log_packet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool log_packet::IsInitialized() const {

  return true;
}

void log_packet::Swap(log_packet* other) {
  if (other != this) {
    depth_.Swap(&other->depth_);
    color_.Swap(&other->color_);
    body_.Swap(&other->body_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata log_packet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = log_packet_descriptor_;
  metadata.reflection = log_packet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
