// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kinect_message.proto

#ifndef PROTOBUF_kinect_5fmessage_2eproto__INCLUDED
#define PROTOBUF_kinect_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class log_packet;
class log_packetDefaultTypeInternal;
extern log_packetDefaultTypeInternal _log_packet_default_instance_;

namespace protobuf_kinect_5fmessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_kinect_5fmessage_2eproto

// ===================================================================

class log_packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:log_packet) */ {
 public:
  log_packet();
  virtual ~log_packet();

  log_packet(const log_packet& from);

  inline log_packet& operator=(const log_packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const log_packet& default_instance();

  static inline const log_packet* internal_default_instance() {
    return reinterpret_cast<const log_packet*>(
               &_log_packet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(log_packet* other);

  // implements Message ----------------------------------------------

  inline log_packet* New() const PROTOBUF_FINAL { return New(NULL); }

  log_packet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const log_packet& from);
  void MergeFrom(const log_packet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(log_packet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 depth = 1;
  int depth_size() const;
  void clear_depth();
  static const int kDepthFieldNumber = 1;
  ::google::protobuf::uint32 depth(int index) const;
  void set_depth(int index, ::google::protobuf::uint32 value);
  void add_depth(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      depth() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_depth();

  // repeated bytes color = 2;
  int color_size() const;
  void clear_color();
  static const int kColorFieldNumber = 2;
  const ::std::string& color(int index) const;
  ::std::string* mutable_color(int index);
  void set_color(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_color(int index, ::std::string&& value);
  #endif
  void set_color(int index, const char* value);
  void set_color(int index, const void* value, size_t size);
  ::std::string* add_color();
  void add_color(const ::std::string& value);
  #if LANG_CXX11
  void add_color(::std::string&& value);
  #endif
  void add_color(const char* value);
  void add_color(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& color() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_color();

  // repeated double body = 3;
  int body_size() const;
  void clear_body();
  static const int kBodyFieldNumber = 3;
  double body(int index) const;
  void set_body(int index, double value);
  void add_body(double value);
  const ::google::protobuf::RepeatedField< double >&
      body() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_body();

  // @@protoc_insertion_point(class_scope:log_packet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > depth_;
  ::google::protobuf::RepeatedPtrField< ::std::string> color_;
  ::google::protobuf::RepeatedField< double > body_;
  friend struct protobuf_kinect_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// log_packet

// repeated uint32 depth = 1;
inline int log_packet::depth_size() const {
  return depth_.size();
}
inline void log_packet::clear_depth() {
  depth_.Clear();
}
inline ::google::protobuf::uint32 log_packet::depth(int index) const {
  // @@protoc_insertion_point(field_get:log_packet.depth)
  return depth_.Get(index);
}
inline void log_packet::set_depth(int index, ::google::protobuf::uint32 value) {
  depth_.Set(index, value);
  // @@protoc_insertion_point(field_set:log_packet.depth)
}
inline void log_packet::add_depth(::google::protobuf::uint32 value) {
  depth_.Add(value);
  // @@protoc_insertion_point(field_add:log_packet.depth)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
log_packet::depth() const {
  // @@protoc_insertion_point(field_list:log_packet.depth)
  return depth_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
log_packet::mutable_depth() {
  // @@protoc_insertion_point(field_mutable_list:log_packet.depth)
  return &depth_;
}

// repeated bytes color = 2;
inline int log_packet::color_size() const {
  return color_.size();
}
inline void log_packet::clear_color() {
  color_.Clear();
}
inline const ::std::string& log_packet::color(int index) const {
  // @@protoc_insertion_point(field_get:log_packet.color)
  return color_.Get(index);
}
inline ::std::string* log_packet::mutable_color(int index) {
  // @@protoc_insertion_point(field_mutable:log_packet.color)
  return color_.Mutable(index);
}
inline void log_packet::set_color(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:log_packet.color)
  color_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void log_packet::set_color(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:log_packet.color)
  color_.Mutable(index)->assign(std::move(value));
}
#endif
inline void log_packet::set_color(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  color_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:log_packet.color)
}
inline void log_packet::set_color(int index, const void* value, size_t size) {
  color_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:log_packet.color)
}
inline ::std::string* log_packet::add_color() {
  // @@protoc_insertion_point(field_add_mutable:log_packet.color)
  return color_.Add();
}
inline void log_packet::add_color(const ::std::string& value) {
  color_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:log_packet.color)
}
#if LANG_CXX11
inline void log_packet::add_color(::std::string&& value) {
  color_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:log_packet.color)
}
#endif
inline void log_packet::add_color(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  color_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:log_packet.color)
}
inline void log_packet::add_color(const void* value, size_t size) {
  color_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:log_packet.color)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
log_packet::color() const {
  // @@protoc_insertion_point(field_list:log_packet.color)
  return color_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
log_packet::mutable_color() {
  // @@protoc_insertion_point(field_mutable_list:log_packet.color)
  return &color_;
}

// repeated double body = 3;
inline int log_packet::body_size() const {
  return body_.size();
}
inline void log_packet::clear_body() {
  body_.Clear();
}
inline double log_packet::body(int index) const {
  // @@protoc_insertion_point(field_get:log_packet.body)
  return body_.Get(index);
}
inline void log_packet::set_body(int index, double value) {
  body_.Set(index, value);
  // @@protoc_insertion_point(field_set:log_packet.body)
}
inline void log_packet::add_body(double value) {
  body_.Add(value);
  // @@protoc_insertion_point(field_add:log_packet.body)
}
inline const ::google::protobuf::RepeatedField< double >&
log_packet::body() const {
  // @@protoc_insertion_point(field_list:log_packet.body)
  return body_;
}
inline ::google::protobuf::RepeatedField< double >*
log_packet::mutable_body() {
  // @@protoc_insertion_point(field_mutable_list:log_packet.body)
  return &body_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_kinect_5fmessage_2eproto__INCLUDED
