// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kinect_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "kinect_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class log_packetDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<log_packet> {
} _log_packet_default_instance_;

namespace protobuf_kinect_5fmessage_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, depth_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(log_packet, body_),
  ~0u,
  ~0u,
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(log_packet)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_log_packet_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "kinect_message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _log_packet_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _log_packet_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\024kinect_message.proto\"8\n\nlog_packet\022\r\n\005"
      "depth\030\001 \003(\r\022\r\n\005color\030\002 \003(\014\022\014\n\004body\030\003 \003(\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 80);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kinect_message.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_kinect_5fmessage_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int log_packet::kDepthFieldNumber;
const int log_packet::kColorFieldNumber;
const int log_packet::kBodyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

log_packet::log_packet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_kinect_5fmessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:log_packet)
}
log_packet::log_packet(const log_packet& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      depth_(from.depth_),
      color_(from.color_),
      body_(from.body_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:log_packet)
}

void log_packet::SharedCtor() {
  _cached_size_ = 0;
}

log_packet::~log_packet() {
  // @@protoc_insertion_point(destructor:log_packet)
  SharedDtor();
}

void log_packet::SharedDtor() {
}

void log_packet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* log_packet::descriptor() {
  protobuf_kinect_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_kinect_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const log_packet& log_packet::default_instance() {
  protobuf_kinect_5fmessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

log_packet* log_packet::New(::google::protobuf::Arena* arena) const {
  log_packet* n = new log_packet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void log_packet::Clear() {
// @@protoc_insertion_point(message_clear_start:log_packet)
  depth_.Clear();
  color_.Clear();
  body_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool log_packet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:log_packet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 depth = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 8u, input, this->mutable_depth())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_depth())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes color = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double body = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 25u, input, this->mutable_body())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(26u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_body())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:log_packet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:log_packet)
  return false;
#undef DO_
}

void log_packet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:log_packet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 depth = 1;
  for (int i = 0, n = this->depth_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      1, this->depth(i), output);
  }

  // repeated bytes color = 2;
  for (int i = 0, n = this->color_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->color(i), output);
  }

  // repeated double body = 3;
  for (int i = 0, n = this->body_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      3, this->body(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:log_packet)
}

::google::protobuf::uint8* log_packet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:log_packet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 depth = 1;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt32ToArray(1, this->depth_, target);

  // repeated bytes color = 2;
  for (int i = 0, n = this->color_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->color(i), target);
  }

  // repeated double body = 3;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteDoubleToArray(3, this->body_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:log_packet)
  return target;
}

size_t log_packet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:log_packet)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated uint32 depth = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->depth_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->depth_size());
    total_size += data_size;
  }

  // repeated bytes color = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->color_size());
  for (int i = 0, n = this->color_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->color(i));
  }

  // repeated double body = 3;
  {
    unsigned int count = this->body_size();
    size_t data_size = 8UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->body_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void log_packet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:log_packet)
  GOOGLE_DCHECK_NE(&from, this);
  const log_packet* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const log_packet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:log_packet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:log_packet)
    MergeFrom(*source);
  }
}

void log_packet::MergeFrom(const log_packet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:log_packet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  depth_.MergeFrom(from.depth_);
  color_.MergeFrom(from.color_);
  body_.MergeFrom(from.body_);
}

void log_packet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:log_packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void log_packet::CopyFrom(const log_packet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:log_packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool log_packet::IsInitialized() const {
  return true;
}

void log_packet::Swap(log_packet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void log_packet::InternalSwap(log_packet* other) {
  depth_.InternalSwap(&other->depth_);
  color_.InternalSwap(&other->color_);
  body_.InternalSwap(&other->body_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata log_packet::GetMetadata() const {
  protobuf_kinect_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_kinect_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// log_packet

// repeated uint32 depth = 1;
int log_packet::depth_size() const {
  return depth_.size();
}
void log_packet::clear_depth() {
  depth_.Clear();
}
::google::protobuf::uint32 log_packet::depth(int index) const {
  // @@protoc_insertion_point(field_get:log_packet.depth)
  return depth_.Get(index);
}
void log_packet::set_depth(int index, ::google::protobuf::uint32 value) {
  depth_.Set(index, value);
  // @@protoc_insertion_point(field_set:log_packet.depth)
}
void log_packet::add_depth(::google::protobuf::uint32 value) {
  depth_.Add(value);
  // @@protoc_insertion_point(field_add:log_packet.depth)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
log_packet::depth() const {
  // @@protoc_insertion_point(field_list:log_packet.depth)
  return depth_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
log_packet::mutable_depth() {
  // @@protoc_insertion_point(field_mutable_list:log_packet.depth)
  return &depth_;
}

// repeated bytes color = 2;
int log_packet::color_size() const {
  return color_.size();
}
void log_packet::clear_color() {
  color_.Clear();
}
const ::std::string& log_packet::color(int index) const {
  // @@protoc_insertion_point(field_get:log_packet.color)
  return color_.Get(index);
}
::std::string* log_packet::mutable_color(int index) {
  // @@protoc_insertion_point(field_mutable:log_packet.color)
  return color_.Mutable(index);
}
void log_packet::set_color(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:log_packet.color)
  color_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void log_packet::set_color(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:log_packet.color)
  color_.Mutable(index)->assign(std::move(value));
}
#endif
void log_packet::set_color(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  color_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:log_packet.color)
}
void log_packet::set_color(int index, const void* value, size_t size) {
  color_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:log_packet.color)
}
::std::string* log_packet::add_color() {
  // @@protoc_insertion_point(field_add_mutable:log_packet.color)
  return color_.Add();
}
void log_packet::add_color(const ::std::string& value) {
  color_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:log_packet.color)
}
#if LANG_CXX11
void log_packet::add_color(::std::string&& value) {
  color_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:log_packet.color)
}
#endif
void log_packet::add_color(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  color_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:log_packet.color)
}
void log_packet::add_color(const void* value, size_t size) {
  color_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:log_packet.color)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
log_packet::color() const {
  // @@protoc_insertion_point(field_list:log_packet.color)
  return color_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
log_packet::mutable_color() {
  // @@protoc_insertion_point(field_mutable_list:log_packet.color)
  return &color_;
}

// repeated double body = 3;
int log_packet::body_size() const {
  return body_.size();
}
void log_packet::clear_body() {
  body_.Clear();
}
double log_packet::body(int index) const {
  // @@protoc_insertion_point(field_get:log_packet.body)
  return body_.Get(index);
}
void log_packet::set_body(int index, double value) {
  body_.Set(index, value);
  // @@protoc_insertion_point(field_set:log_packet.body)
}
void log_packet::add_body(double value) {
  body_.Add(value);
  // @@protoc_insertion_point(field_add:log_packet.body)
}
const ::google::protobuf::RepeatedField< double >&
log_packet::body() const {
  // @@protoc_insertion_point(field_list:log_packet.body)
  return body_;
}
::google::protobuf::RepeatedField< double >*
log_packet::mutable_body() {
  // @@protoc_insertion_point(field_mutable_list:log_packet.body)
  return &body_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
